#!/usr/bin/env python
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

import sys
import subprocess

print "Running karma tests, brb"

output = subprocess.check_output("python test.py", shell=True)

# redirect stdin to an open file handle
sys.stdin = open('/dev/tty')

exit = -1
while exit == -1:
  proceed = raw_input(output + "\n\nProceed with commit? (y/n) ")
  if proceed == 'y':
    exit = 0
  elif proceed == 'n':
    exit = 1

sys.exit(exit)